In [4]:
import torch.nn as nn
import torch

In [18]:
class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.dropout = nn.Dropout(p=0.5)
        self.fc_reg = nn.Linear(100, 1)
        self.fc_cls = nn.Linear(100, 5)
    def forward(self, x):
        x = self.dropout(x)
        reg = self.fc_reg(x)
        cls = self.fc_cls(x)
        print(reg)
        print(cls.softmax(dim=-1))
        

In [19]:
m = Model()
m.training

True

In [20]:
x = torch.randn(1, 100)

In [21]:
m(x)

tensor([[0.1047]], grad_fn=<AddmmBackward0>)
tensor([[0.2261, 0.2517, 0.2566, 0.1510, 0.1147]], grad_fn=<SoftmaxBackward0>)


In [24]:
m(x)

tensor([[0.1522]], grad_fn=<AddmmBackward0>)
tensor([[0.2016, 0.3076, 0.2812, 0.1095, 0.1001]], grad_fn=<SoftmaxBackward0>)


In [25]:
m.eval()
m.training

False

In [26]:
m(x)

tensor([[-0.1970]], grad_fn=<AddmmBackward0>)
tensor([[0.1886, 0.2165, 0.2908, 0.1375, 0.1666]], grad_fn=<SoftmaxBackward0>)
